# Intro to numpy
NumPy (Numerical Python) is a foundational Python library for numerical computing. It provides efficient support for multi-dimensional arrays, an extensive collection of mathematical functions, and advanced capabilities like broadcasting. NumPy is a cornerstone of scientific computing in Python, enabling efficient data manipulation and mathematical operations. It seamlessly integrates with other data analysis and visualization libraries, making it a vital tool for various scientific and data analysis tasks.

In [1]:
import numpy as np

## Datatypes and attributes
Numpys main datatype is ndarray which stands for ndimensional array

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
#this helps one to figure out the anatomy of a created matrix or vector. It provides the shape of the matrix.
a1.shape

(3,)

In [5]:
#.ndim provides the dimensions of a matrix. It shows whether the matrix is 1dimensional, 2, 3 or any dimension.
a1.ndim

1

In [6]:
#.dtype attribute helps to determine the datatypes within an array of numbers.If say an array contains 2 or more datatypes, then one will be automatically chosen and the rest converted to suit that one.
a1.dtype

dtype('int64')

In [7]:
#.size shows the number of elements in an array
a1.size

3

In [8]:
#numpy.ones this returns a new array with a given shape and type filled with ones
ones=np.ones((3,3))

In [9]:
zeros=np.zeros((3,3))

In [10]:
#numpy.arange(start_value,stop_value,step_value) could be used to create an array with different consecutive numbers
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
#numpy.random.randint(0,10, size=(3,5)). This creates a 3 by 5 matrix with random values ranging from 0-10 
np.random.randint(0,10, size=(3,5))

array([[0, 2, 2, 8, 8],
       [7, 2, 8, 1, 5],
       [9, 3, 3, 6, 6]])

In [12]:
#numpy.random.random((shape)). This creates an m by n matrix with values between 0 and 1.
np.random.random((20,13))

array([[0.07164474, 0.63728428, 0.27986469, 0.53325613, 0.60743253,
        0.90730079, 0.06944177, 0.80451505, 0.19464559, 0.2931165 ,
        0.82241898, 0.11174271, 0.59130651],
       [0.73445355, 0.44738463, 0.93821716, 0.73490766, 0.58092829,
        0.20292088, 0.04090493, 0.53584054, 0.10337789, 0.79103466,
        0.48087473, 0.95312211, 0.7683637 ],
       [0.20080228, 0.97469206, 0.89009335, 0.94032342, 0.52407675,
        0.56923193, 0.25859055, 0.61736996, 0.57232941, 0.02288147,
        0.54801333, 0.14557932, 0.2025643 ],
       [0.87604974, 0.02167482, 0.23560067, 0.27979767, 0.53813289,
        0.23403945, 0.12088969, 0.62780684, 0.60193561, 0.13387804,
        0.21574466, 0.15453657, 0.57757275],
       [0.15499915, 0.17526018, 0.67410575, 0.84342803, 0.37061013,
        0.29879285, 0.82187208, 0.56418199, 0.45521848, 0.18457669,
        0.49606493, 0.62043656, 0.77782851],
       [0.43083369, 0.22766059, 0.5838843 , 0.01657088, 0.53557676,
        0.50719762, 0.94239

In [13]:
#numpy.random.seed(value). This makes sure that the random numbers in the cell that is being run are the same.
np.random.seed(7) 
np.random.randint(0,10, size=(3,5))

array([[4, 9, 6, 3, 3],
       [7, 7, 9, 7, 8],
       [9, 8, 7, 6, 4]])

## Viewing arrays and matrices

## Arithmetic

In [14]:
ones=np.ones(3)
w=a1+ones
x=a1*ones
w,x

(array([2., 3., 4.]), array([1., 2., 3.]))

In [15]:
#Numpy broadcasting. This refers to the rules used by numpy in manipulating arrays. This is the general matrix arithmetic manipulation rules. 
#please find more on the numpy documentation site.
a4=np.random.randint(1,5,size=(3,1))
a5=np.random.random((3,3))
a4,a5

(array([[1],
        [4],
        [4]]),
 array([[0.38094113, 0.06593635, 0.2881456 ],
        [0.90959353, 0.21338535, 0.45212396],
        [0.93120602, 0.02489923, 0.60054892]]))

In [16]:
#Now multiplying the smaller array by the larger one. Numpy can only multiply the arrays when their shapes are equal or when one of them is equal to one.
a4*a5

array([[0.38094113, 0.06593635, 0.2881456 ],
       [3.63837411, 0.85354141, 1.80849585],
       [3.72482408, 0.09959691, 2.40219567]])

In [17]:
#Now lets try the other way around
a5*a4

array([[0.38094113, 0.06593635, 0.2881456 ],
       [3.63837411, 0.85354141, 1.80849585],
       [3.72482408, 0.09959691, 2.40219567]])

In [18]:
#You can run this cell to see what I'm talking about. 
a6=np.random.randint(2,12,size=(3,2))
a7=np.random.random((4,5))
a6*a7
#We would have to reshape one of the matrices. We'll talk about this in the future.

ValueError: operands could not be broadcast together with shapes (3,2) (4,5) 

In [19]:
#Division
a4/a5

array([[  2.62507751,  15.166142  ,   3.47046772],
       [  4.39756867,  18.74542902,   8.84713118],
       [  4.29550488, 160.6475539 ,   6.66057316]])

In [20]:
# floor division (//) removes decimals (rounds the numbers)
a4//a5

array([[  2.,  15.,   3.],
       [  4.,  18.,   8.],
       [  4., 160.,   6.]])

In [21]:
#exponents. To raise an array to a certain number, use '**'
a4**3

array([[ 1],
       [64],
       [64]])

In [22]:
#You conld also use numpy.square() to raise an array to 2.
np.square(a4)

array([[ 1],
       [16],
       [16]])

In [23]:
# modulo '%'. This shows the remainder value when two numbers divide.
a4%a5

array([[0.23811773, 0.0109548 , 0.1355632 ],
       [0.36162589, 0.15906364, 0.38300831],
       [0.27517592, 0.01612359, 0.3967065 ]])

In [24]:
#You could also use numpy.mod()
np.mod(a4,a5)

array([[0.23811773, 0.0109548 , 0.1355632 ],
       [0.36162589, 0.15906364, 0.38300831],
       [0.27517592, 0.01612359, 0.3967065 ]])

In [25]:
#numpy.log. computes the natural logarithm of an array
np.log(a4)

array([[0.        ],
       [1.38629436],
       [1.38629436]])

In [26]:
np.log2(a4)

array([[0.],
       [2.],
       [2.]])

In [27]:
#This calculates the exponential of an array or number.
np.exp(4)

54.598150033144236

## Aggregation
Aggregation is about performing the same operations on a number of things

In [28]:
# np.mean()
# np.max()
# np.std()
# np.var()
# np.sum

## Standard deviation and variance
    These are measures of the spread of data. Variance is the measure of the average degree to which each number is different to the mean.The standard deviation is a measure of how spread out a group of numers is from the mean. The standard deviation is the square root of the variance.

In [29]:
#Variance
var=np.var(a4)

In [30]:
#Standard deviation
np.std(a4)

1.4142135623730951

In [31]:
#This code shows that the standard deviation=the square root of variance
np.sqrt(var)

1.4142135623730951

## Reshape & Transpose

In [32]:
#array.reshape(): this returns an array with a new shape 
a4.reshape(3,1,1)

array([[[1]],

       [[4]],

       [[4]]])

In [33]:
#Transpose: This switches the rows and columns of an array. So it just turns a 3 by 2 matrix into a 2 by 3 matrix for instance.
a4.T

array([[1, 4, 4]])

## Dot product

In [34]:
#array.dot: This is used to compute the dot product of 2 arrays
mat1=np.random.randint(10, size=(5,3))
mat2=np.random.randint(10, size=(5,3))
#np.multiply just multiplies elementwise

In [35]:
from matplotlib import pyplot as plt
from matplotlib.image import imread

# Load and display the image
img = imread('/Users/elman/Documents/GitHub/sample_project/dotpro.png')
plt.imshow(img)
plt.axis('off')  # Turn off axis labels and ticks
plt.show()

In [36]:
#In dot product, the number of columns in the first matrix must be equal to the number of the rows in the second matrix.
#so for the dot product of mat1 and mat2 to work, we'll have to transpose one of them.
mat3=mat1.T
mat3

array([[3, 5, 2, 2, 3],
       [1, 9, 3, 5, 0],
       [9, 1, 2, 7, 9]])

In [37]:
np.dot(mat3,mat2)

array([[ 83,  68,  56],
       [101,  64,  57],
       [170, 132, 151]])

## Dot product example

In [38]:
np.random.seed(0)
#number of jars sold
sales_amounts=np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [39]:
#create a weekly sales dataframe
import pandas as pd
weekly_sales=pd.DataFrame(sales_amounts,
                         index=["Mon","Tues","Wed","Thurs","Fri"],
                         columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [40]:
#create prices array
prices=np.array([10,8,12])

In [41]:
butter_prices=pd.DataFrame(prices.reshape(1,3),
                           index=["Price"],
                           columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [42]:
total_sales=prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [43]:
daily_sales=pd.DataFrame(total_sales.reshape(1,5),
                        index=["Price"],
                        columns=["Mon","Tues","Wed","Thurs","Fri"])
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [44]:
#Now to combine the dail_sales DataFrame to the weekly_sales we'll have to make sure that they have the same number of rows.
daily_sales.shape,weekly_sales.shape

((1, 5), (5, 3))

In [45]:
Daily_sales=daily_sales.T
Daily_sales

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [46]:
weekly_sales["Total($)"]=Daily_sales
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total($)
Mon               12             15              0       240
Tues               3              3              7       138
Wed                9             19             18       458
Thurs              4              6             12       232
Fri                1              6              7       142

## Comparison operators

In [47]:
a4>a5

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [48]:
a4<a5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [49]:
a4==a5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# Sorting arrays

In [50]:
#np.sort():performs an element-wise sorting of arrays from smallest to largest value
np.random.seed(0)
random_array=np.random.randint(20,size=(3,5))
np.sort(random_array)

array([[ 0,  3,  3, 12, 15],
       [ 4,  7,  9, 18, 19],
       [ 1,  6,  6,  7, 12]])

In [51]:
random_array

array([[12, 15,  0,  3,  3],
       [ 7,  9, 19, 18,  4],
       [ 6, 12,  1,  6,  7]])

In [52]:
#np.argsort() sorts the indexes from lowest to highest
np.argsort(random_array)

array([[2, 3, 4, 0, 1],
       [4, 0, 1, 3, 2],
       [2, 0, 3, 4, 1]])